import os
import tempfile
import threading
import unittest
from http.cookiejar import CookieJar
from urllib.parse import urlencode
from urllib.request import HTTPCookieProcessor, Request, build_opener

from admin_server import (
    AdminHandler,
    autogenerated_admin_config,
    check_password,
    fmt_time,
    load_wifi_remote_config,
    make_password_hash,
)
import backup_manager
import config as mesh_config
from database import Database
from http.server import ThreadingHTTPServer


class AdminServerTests(unittest.TestCase):
    def test_autogenerated_admin_config_fills_runtime_paths(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            config = autogenerated_admin_config(tmpdir, {"port": 0, "username": "sysop"})

            self.assertEqual(8080, config["port"])
            self.assertEqual(os.path.join(tmpdir, "meshboard.db"), config["database"]["path"])
            self.assertEqual(os.path.join(tmpdir, "meshtastic_config.json"), config["mesh_config_path"])
            self.assertEqual(os.path.join(tmpdir, "wifi_remote.conf"), config["wifi_remote_config_path"])
            self.assertEqual(os.path.join(tmpdir, "modules", "Games"), config["games_dir"])

    def test_password_hash_round_trip(self):
        hashed = make_password_hash("secret")

        self.assertTrue(check_password("secret", hashed))
        self.assertFalse(check_password("wrong", hashed))

    def test_dashboard_uses_clickable_section_links(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            Database(db_path).record_user_command("!cabn", "CABN")
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/") as response:
                    dashboard = response.read().decode("utf-8")
                for path, label in (
                    ("/users", "Users"),
                    ("/addressbook", "AddressBook"),
                    ("/messages", "Mail"),
                    ("/board", "Message Board"),
                    ("/locations", "Locations"),
                    ("/games", "Games"),
                    ("/backups", "Backups"),
                    ("/checkins", "Check-Ins"),
                    ("/config", "Config"),
                    ("/logs", "Logs"),
                ):
                    self.assertIn(f"<a class='dashboard-link' href='{path}'>", dashboard)
                    self.assertIn(f"<h2>{label}</h2>", dashboard)
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_games_page_toggles_and_imports_plugins(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            games_dir = os.path.join(tmpdir, "Games")
            os.makedirs(games_dir)
            with open(os.path.join(games_dir, "sample_game.py"), "w", encoding="utf-8") as handle:
                handle.write(
                    "menu_name = 'Sample Game'\n\n"
                    "def display_menu():\n"
                    "    return 'Sample Game'\n\n"
                    "def process_command(user_id, command, bbs_system):\n"
                    "    return 'ok'\n"
                )
            Database(db_path)
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
                "games_dir": games_dir,
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/games") as response:
                    games = response.read().decode("utf-8")
                self.assertIn("Sample Game", games)
                self.assertIn("Disable", games)
                self.assertIn("Edit", games)
                self.assertIn("Import Game Plugin", games)

                disable_data = urlencode({"module_name": "sample_game", "enabled": "0"}).encode("utf-8")
                with opener.open(Request(f"{base}/set-game-enabled", data=disable_data, method="POST")):
                    pass
                self.assertFalse(Database(db_path).is_game_enabled("sample_game"))
                with opener.open(f"{base}/games") as response:
                    games = response.read().decode("utf-8")
                self.assertIn("Enable", games)

                with opener.open(f"{base}/edit-game?module_name=sample_game") as response:
                    edit_page = response.read().decode("utf-8")
                self.assertIn("Edit Game Plugin", edit_page)
                self.assertIn("return &#x27;ok&#x27;", edit_page)

                edited_source = (
                    "menu_name = 'Sample Game'\n\n"
                    "def process_command(user_id, command, bbs_system):\n"
                    "    location, message = bbs_system.get_recent_location_or_message(user_id)\n"
                    "    return message or bbs_system.ask_local_ai('say hi')\n"
                )
                edit_data = urlencode({"module_name": "sample_game", "source": edited_source}).encode("utf-8")
                with opener.open(Request(f"{base}/edit-game", data=edit_data, method="POST")):
                    pass
                with open(os.path.join(games_dir, "sample_game.py"), "r", encoding="utf-8") as handle:
                    self.assertIn("ask_local_ai", handle.read())

                plugin_source = (
                    "menu_name = 'Trail Quiz'\n\n"
                    "def process_command(user_id, command, bbs_system):\n"
                    "    return 'Trail Quiz'\n"
                )
                import_data = urlencode({"filename": "trail_quiz.py", "source": plugin_source}).encode("utf-8")
                with opener.open(Request(f"{base}/import-game", data=import_data, method="POST")):
                    pass
                self.assertTrue(os.path.exists(os.path.join(games_dir, "trail_quiz.py")))
                self.assertTrue(Database(db_path).is_game_enabled("trail_quiz"))
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_backup_page_creates_backup_sets_retention_and_restores(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            app_dir = os.path.join(tmpdir, "app")
            backup_dir = os.path.join(tmpdir, "backup-store")
            os.makedirs(app_dir)
            state_file = os.path.join(app_dir, "admin_config.json")
            with open(state_file, "w", encoding="utf-8") as handle:
                handle.write('{"before": true}')
            Database(db_path)
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
                "app_dir": app_dir,
            }
            old_backup_dir = os.environ.get("MESHBOARD_BACKUP_DIR")
            os.environ["MESHBOARD_BACKUP_DIR"] = backup_dir
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/backups") as response:
                    backups = response.read().decode("utf-8")
                self.assertIn("Backup All Now", backups)
                self.assertIn("Daily Retention Days", backups)

                retention_data = urlencode({"retention_days": "3"}).encode("utf-8")
                with opener.open(Request(f"{base}/backup-retention", data=retention_data, method="POST")):
                    pass
                self.assertEqual("3", Database(db_path).get_app_setting(backup_manager.RETENTION_SETTING))

                with opener.open(Request(f"{base}/create-backup", data=b"", method="POST")):
                    pass
                backups = backup_manager.list_backups()
                self.assertEqual(1, len(backups))
                self.assertTrue(backups[0]["filename"].startswith("meshboard-manual-"))

                with open(state_file, "w", encoding="utf-8") as handle:
                    handle.write('{"before": false}')
                restore_data = urlencode({"filename": backups[0]["filename"]}).encode("utf-8")
                with opener.open(Request(f"{base}/restore-backup", data=restore_data, method="POST")):
                    pass
                with open(state_file, "r", encoding="utf-8") as handle:
                    self.assertEqual('{"before": true}', handle.read())
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
                if old_backup_dir is None:
                    os.environ.pop("MESHBOARD_BACKUP_DIR", None)
                else:
                    os.environ["MESHBOARD_BACKUP_DIR"] = old_backup_dir

    def test_config_page_updates_runtime_config_and_backup_retention(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            mesh_config_path = os.path.join(tmpdir, "meshtastic_config.json")
            wifi_remote_path = os.path.join(tmpdir, "wifi_remote.conf")
            mesh_config.save_config(mesh_config.DEFAULT_CONFIG, mesh_config_path)
            with open(wifi_remote_path, "w", encoding="utf-8") as handle:
                handle.write(
                    "\n".join(
                        [
                            "ENABLED=false",
                            "INTERFACE=auto",
                            "CONNECTION_NAME=MeshBoardRemoteHotspot",
                            "CONNECT_ONLY_WHEN_OFFLINE=true",
                            "PREFER_VISIBLE_HOTSPOT=true",
                            "CHECK_INTERVAL_SECONDS=60",
                            "HOTSPOT_1_ENABLED=true",
                            "HOTSPOT_1_SSID=OldPhone",
                            "HOTSPOT_1_PSK=keep-secret",
                        ]
                    )
                    + "\n"
                )
            Database(db_path)
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
                "mesh_config_path": mesh_config_path,
                "wifi_remote_config_path": wifi_remote_path,
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/config") as response:
                    page = response.read().decode("utf-8")
                self.assertIn("Daily Retention Days", page)
                self.assertIn("ACK Retries", page)
                self.assertIn("Local AI", page)
                self.assertIn("Remote Hotspot WiFi", page)
                self.assertIn("Generated System Settings", page)
                self.assertIn("Remote WiFi Config", page)
                self.assertIn("Password saved; leave blank to keep it.", page)

                data = urlencode(
                    {
                        "backup_retention_days": "14",
                        "connection_type": "wifi",
                        "device_path": "/dev/serial/by-id/test-radio",
                        "wifi_hostname": "192.168.1.50",
                        "wifi_port": "4404",
                        "bluetooth_address": "AA:BB:CC:DD:EE:FF",
                        "max_text_length": "120",
                        "chunk_delay_seconds": "0.2",
                        "ack_timeout_seconds": "9",
                        "ack_retries": "4",
                        "reconnect_delay_seconds": "12",
                        "gps_freshness_seconds": "600",
                        "whats_here_radius_meters": "200",
                        "nearby_radius_meters": "1500",
                        "sync_on_startup": "1",
                        "sync_from_mesh": "1",
                        "sync_interval_seconds": "1800",
                        "minimum_valid_epoch": "1704067200",
                        "maximum_future_seconds": "86400",
                        "local_ai_enabled": "1",
                        "local_ai_url": "http://127.0.0.1:11434/api/generate",
                        "local_ai_model": "tiny-local",
                        "local_ai_timeout_seconds": "30",
                        "local_ai_idle_shutdown_seconds": "1200",
                        "local_ai_startup_timeout_seconds": "60",
                        "wifi_remote_enabled": "1",
                        "wifi_remote_interface": "wlan0",
                        "wifi_remote_connection_name": "MeshBoardRemoteHotspot",
                        "wifi_remote_connect_only_when_offline": "1",
                        "wifi_remote_prefer_visible_hotspot": "1",
                        "wifi_remote_check_interval_seconds": "45",
                        "hotspot_1_enabled": "1",
                        "hotspot_1_ssid": "MyPhone",
                        "hotspot_2_enabled": "1",
                        "hotspot_2_ssid": "BackupPhone",
                        "hotspot_2_psk": "backup-secret",
                    }
                ).encode("utf-8")
                with opener.open(Request(f"{base}/config", data=data, method="POST")):
                    pass

                updated = mesh_config.load_config(mesh_config_path)
                self.assertEqual("14", Database(db_path).get_app_setting(backup_manager.RETENTION_SETTING))
                self.assertEqual("wifi", updated["connection_type"])
                self.assertEqual("192.168.1.50", updated["wifi"]["hostname"])
                self.assertEqual(4404, updated["wifi"]["port"])
                self.assertEqual(4, updated["meshtastic"]["ack_retries"])
                self.assertEqual(600, updated["gps"]["freshness_seconds"])
                self.assertFalse(updated["time_sync"]["sync_from_host"])
                self.assertTrue(updated["time_sync"]["sync_from_mesh"])
                self.assertTrue(updated["local_ai"]["enabled"])
                self.assertEqual("tiny-local", updated["local_ai"]["model"])
                self.assertEqual(1200, updated["local_ai"]["idle_shutdown_seconds"])
                self.assertEqual(60, updated["local_ai"]["startup_timeout_seconds"])
                wifi_remote = load_wifi_remote_config(wifi_remote_path)
                self.assertTrue(wifi_remote["enabled"])
                self.assertEqual("wlan0", wifi_remote["interface"])
                self.assertEqual(45, wifi_remote["check_interval_seconds"])
                self.assertEqual("MyPhone", wifi_remote["hotspots"][0]["ssid"])
                self.assertEqual("keep-secret", wifi_remote["hotspots"][0]["psk"])
                self.assertEqual("BackupPhone", wifi_remote["hotspots"][1]["ssid"])
                self.assertEqual("backup-secret", wifi_remote["hotspots"][1]["psk"])
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_test_commands_emulates_mesh_messages(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            mesh_config_path = os.path.join(tmpdir, "meshtastic_config.json")
            config_data = mesh_config.DEFAULT_CONFIG.copy()
            config_data["database"] = {"path": db_path}
            mesh_config.save_config(config_data, mesh_config_path)
            Database(db_path)
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
                "mesh_config_path": mesh_config_path,
                "wifi_remote_config_path": os.path.join(tmpdir, "wifi_remote.conf"),
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/test-commands") as response:
                    page = response.read().decode("utf-8")
                self.assertIn("Test Commands", page)
                self.assertIn("Fake Node ID", page)

                data = urlencode({"node_id": "!admintest", "command": "top", "action": "send"}).encode("utf-8")
                with opener.open(Request(f"{base}/test-commands", data=data, method="POST")) as response:
                    page = response.read().decode("utf-8")
                self.assertIn("Main Menu", page)

                data = urlencode({"node_id": "!admintest", "command": "3", "action": "send"}).encode("utf-8")
                with opener.open(Request(f"{base}/test-commands", data=data, method="POST")) as response:
                    page = response.read().decode("utf-8")
                self.assertIn("Mail", page)
                self.assertIn("Inbox", page)

                data = urlencode({"node_id": "!admintest", "action": "reset"}).encode("utf-8")
                with opener.open(Request(f"{base}/test-commands", data=data, method="POST")) as response:
                    page = response.read().decode("utf-8")
                self.assertIn("Fake node session reset.", page)
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_login_and_delete_message(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            db = Database(db_path)
            message_id = db.send_message("!from", "!to", "remove me")
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/messages") as response:
                    messages = response.read().decode("utf-8")
                self.assertIn("remove me", messages)
                self.assertIn("Edit", messages)
                self.assertIn("Archive", messages)
                self.assertIn("/message-archives", messages)

                edit_data = urlencode(
                    {"id": str(message_id), "sender_id": "!from", "recipient_id": "!to", "body": "edited body"}
                ).encode("utf-8")
                with opener.open(Request(f"{base}/edit-message", data=edit_data, method="POST")):
                    pass
                self.assertIn("edited body", Database(db_path).inbox("!to", include_deleted=True)[0]["body"])

                archive_data = urlencode({"id": str(message_id)}).encode("utf-8")
                with opener.open(Request(f"{base}/archive-message", data=archive_data, method="POST")):
                    pass
                self.assertEqual([], Database(db_path).inbox("!to"))
                self.assertEqual("edited body", Database(db_path).archived_inbox("!to")[0]["body"])
                with opener.open(f"{base}/messages") as response:
                    messages = response.read().decode("utf-8")
                self.assertNotIn("edited body", messages)
                with opener.open(f"{base}/message-archives") as response:
                    archived = response.read().decode("utf-8")
                self.assertIn("Archived Mail", archived)
                self.assertIn("edited body", archived)
                self.assertIn("/messages", archived)

                delete_data = urlencode({"id": str(message_id)}).encode("utf-8")
                with opener.open(Request(f"{base}/delete-message", data=delete_data, method="POST")):
                    pass

                self.assertEqual([], Database(db_path).inbox("!to", include_deleted=True))
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_users_page_shows_recent_activity_details(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            db = Database(db_path)
            db.record_user_command("!cabn", "CABN")
            db.record_user_command("!cabn")
            db.record_user_command("!raw")
            db.mark_mail_checked("!cabn", 1788830000)
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/users") as response:
                    users = response.read().decode("utf-8")
                self.assertIn("Users", users)
                self.assertIn("<th>User</th>", users)
                self.assertIn("<th>AddressBook</th>", users)
                self.assertIn("<th>Commands</th>", users)
                self.assertIn("<th>First Interaction</th>", users)
                self.assertIn("<th>Last Interaction</th>", users)
                self.assertIn("<th>Checked Mail</th>", users)
                self.assertIn("CABN", users)
                self.assertIn("!cabn", users)
                self.assertIn("!raw", users)
                self.assertIn(fmt_time(1788830000), users)
                self.assertIn("<td>No</td>", users)
                self.assertIn("<td>2</td>", users)

                edit_data = urlencode(
                    {"node_id": "!raw", "display_name": "RAW1", "mail_listed": "1", "command_count": "7"}
                ).encode("utf-8")
                with opener.open(Request(f"{base}/edit-user", data=edit_data, method="POST")):
                    pass
                raw = Database(db_path).get_user("!raw")
                self.assertEqual("RAW1", raw["display_name"])
                self.assertEqual(1, raw["mail_listed"])
                self.assertEqual(7, raw["command_count"])
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_board_category_submenu_filters_and_deletes(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            db = Database(db_path)
            db.set_display_name("!author", "CABN")
            news_id = db.create_board_post("news", "!author", "road is clear")
            db.create_board_post("trade", "!seller", "extra batteries")
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/board?category=news") as response:
                    board = response.read().decode("utf-8")
                self.assertIn("Local News", board)
                self.assertIn("road is clear", board)
                self.assertIn("CABN", board)
                self.assertIn("Edit", board)
                self.assertNotIn("extra batteries", board)
                self.assertNotIn("Main Menu Header", board)

                edit_data = urlencode(
                    {"id": str(news_id), "category": "rumors", "author_id": "!author", "body": "edited rumor"}
                ).encode("utf-8")
                with opener.open(Request(f"{base}/edit-board", data=edit_data, method="POST")) as response:
                    redirected = response.geturl()
                self.assertIn("/board?edited=1&category=rumors", redirected)
                edited = Database(db_path).get_board_post(news_id)
                self.assertEqual("rumors", edited["category"])
                self.assertEqual("edited rumor", edited["body"])

                delete_data = urlencode({"id": str(news_id), "category": "rumors"}).encode("utf-8")
                with opener.open(Request(f"{base}/delete-board", data=delete_data, method="POST")) as response:
                    redirected = response.geturl()

                self.assertIn("/board?deleted=1&category=rumors", redirected)
                with opener.open(f"{base}/board?category=rumors") as response:
                    board = response.read().decode("utf-8")
                self.assertNotIn("edited rumor", board)
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_location_and_checkin_edit_actions(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            db = Database(db_path)
            location_id = db.save_location("!loc", "LOC1", 35.0, -97.0, None, "old note")
            checkin_id = db.create_checkin_event("!net", "Old Net", starts_at=1000, duration_seconds=86400)
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/locations") as response:
                    locations = response.read().decode("utf-8")
                self.assertIn("Edit", locations)
                location_data = urlencode(
                    {
                        "id": str(location_id),
                        "creator_id": "!loc",
                        "creator_name": "LOC2",
                        "latitude": "36.5",
                        "longitude": "-98.5",
                        "altitude": "123",
                        "visibility": "public",
                        "body": "new note",
                    }
                ).encode("utf-8")
                with opener.open(Request(f"{base}/edit-location", data=location_data, method="POST")):
                    pass
                edited_location = Database(db_path).active_locations()[0]
                self.assertEqual("LOC2", edited_location["creator_name"])
                self.assertEqual("new note", edited_location["body"])
                self.assertEqual(36.5, edited_location["latitude"])

                with opener.open(f"{base}/checkins") as response:
                    checkins = response.read().decode("utf-8")
                self.assertIn("Edit", checkins)
                checkin_data = urlencode(
                    {
                        "id": str(checkin_id),
                        "title": "New Net",
                        "created_by": "!net",
                        "starts_at": "2000",
                        "ends_at": "3000",
                        "closed": "1",
                    }
                ).encode("utf-8")
                with opener.open(Request(f"{base}/edit-checkin", data=checkin_data, method="POST")):
                    pass
                with Database(db_path).connect() as conn:
                    edited_checkin = conn.execute("SELECT * FROM checkin_events WHERE id = ?", (checkin_id,)).fetchone()
                self.assertEqual("New Net", edited_checkin["title"])
                self.assertEqual(3000, edited_checkin["ends_at"])
                self.assertEqual(1, edited_checkin["closed"])
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)

    def test_addressbook_page_lists_and_removes_contacts(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            db_path = os.path.join(tmpdir, "meshboard.db")
            db = Database(db_path)
            db.set_mail_listed("!cabn", "CABN", True)
            db.set_display_name("!seen", "SEEN")
            config = {
                "host": "127.0.0.1",
                "port": 0,
                "username": "sysop",
                "password_hash": make_password_hash("secret"),
                "session_secret": "test-secret",
                "database": {"path": db_path},
            }
            server = ThreadingHTTPServer(("127.0.0.1", 0), AdminHandler)
            server.config = config
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                base = f"http://127.0.0.1:{server.server_address[1]}"
                opener = build_opener(HTTPCookieProcessor(CookieJar()))
                login_data = urlencode({"username": "sysop", "password": "secret"}).encode("utf-8")
                with opener.open(Request(f"{base}/login", data=login_data, method="POST")):
                    pass

                with opener.open(f"{base}/addressbook") as response:
                    addressbook = response.read().decode("utf-8")
                self.assertIn("AddressBook", addressbook)
                self.assertIn("CABN", addressbook)
                self.assertIn("!cabn", addressbook)
                self.assertIn("Edit", addressbook)
                self.assertNotIn("!seen", addressbook)

                with opener.open(f"{base}/edit-addressbook?node_id=%21cabn") as response:
                    edit_page = response.read().decode("utf-8")
                self.assertIn("Edit AddressBook ID", edit_page)
                self.assertIn("CABN", edit_page)

                edit_data = urlencode({"node_id": "!cabn", "display_name": "HOME"}).encode("utf-8")
                with opener.open(Request(f"{base}/edit-addressbook", data=edit_data, method="POST")):
                    pass
                self.assertEqual("HOME", Database(db_path).get_user("!cabn")["display_name"])

                remove_data = urlencode({"node_id": "!cabn"}).encode("utf-8")
                with opener.open(Request(f"{base}/remove-addressbook", data=remove_data, method="POST")):
                    pass

                self.assertEqual([], Database(db_path).list_mail_contacts())
                self.assertIsNotNone(Database(db_path).get_user("!cabn"))
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
