#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-$HOME/MeshBoard}"
SERVICE_NAME="${SERVICE_NAME:-meshboard.service}"
ADMIN_USERNAME="${MESHBOARD_ADMIN_USERNAME:-sysop}"
ADMIN_PASSWORD="${MESHBOARD_ADMIN_PASSWORD:-}"
ADMIN_CREDENTIALS_FILE="${MESHBOARD_ADMIN_CREDENTIALS_FILE:-$APP_DIR/admin_credentials.txt}"
ADMIN_INSTALL_INFO_FILE="${MESHBOARD_ADMIN_INSTALL_INFO_FILE:-$APP_DIR/.admin_install_info}"
INSTALL_OLLAMA="${MESHBOARD_INSTALL_OLLAMA:-true}"
OLLAMA_MODEL="${MESHBOARD_OLLAMA_MODEL:-tinyllama}"

if [[ ! -f "bbs_system.py" ]]; then
    echo "Run this script from the MeshBoard repository root."
    exit 1
fi

sudo apt update
sudo apt install -y python3-venv python3-pip python3-serial git rsync cron curl
sudo systemctl enable --now cron || true
if command -v nmcli >/dev/null 2>&1; then
    nmcli_path="$(command -v nmcli)"
    printf '%s ALL=(root) NOPASSWD: %s\n' "$(id -un)" "$nmcli_path" | sudo tee /etc/sudoers.d/meshboard-nmcli >/dev/null
    sudo chmod 440 /etc/sudoers.d/meshboard-nmcli
fi

mkdir -p "$APP_DIR"
SOURCE_DIR="$(pwd -P)"
TARGET_DIR="$(cd "$APP_DIR" && pwd -P)"
if [[ "$SOURCE_DIR" != "$TARGET_DIR" ]]; then
    rsync -a --delete \
        --exclude ".git" \
        --exclude "__pycache__" \
        --exclude "*.pyc" \
        --exclude ".venv" \
        --exclude "meshboard.db" \
        --exclude "meshtastic_config.json" \
        --exclude "admin_config.json" \
        --exclude "wifi_remote.conf" \
        --exclude "wifi-connect.log" \
        ./ "$APP_DIR/"
fi

python3 -m venv "$APP_DIR/.venv"
"$APP_DIR/.venv/bin/python" -m pip install --upgrade pip
"$APP_DIR/.venv/bin/python" -m pip install meshtastic

if [[ "$INSTALL_OLLAMA" == "true" ]]; then
    machine="$(uname -m)"
    arch_bits="$(getconf LONG_BIT || echo 0)"
    if [[ "$machine" == "armv6l" || "$machine" == "armv7l" || ( "$machine" == arm* && "$arch_bits" == "32" ) ]]; then
        echo "Ollama is not supported on this 32-bit ARM OS; Local AI can still point to another Ollama server."
    elif ! command -v ollama >/dev/null 2>&1; then
        curl -fsSL https://ollama.com/install.sh | sh || echo "Ollama install failed; Local AI will show an install hint until Ollama is available."
    fi
    sudo systemctl disable --now ollama >/dev/null 2>&1 || true
    if command -v ollama >/dev/null 2>&1; then
        (
            ollama serve >/tmp/meshboard-ollama-install.log 2>&1 &
            ollama_pid=$!
            sleep 5
            ollama pull "$OLLAMA_MODEL" || true
            kill "$ollama_pid" >/dev/null 2>&1 || true
            wait "$ollama_pid" >/dev/null 2>&1 || true
        )
    fi
fi

if [[ ! -f "$APP_DIR/meshtastic_config.json" ]]; then
    (
        cd "$APP_DIR"
        "$APP_DIR/.venv/bin/python" setup.py || true
    )
fi
if [[ ! -f "$APP_DIR/meshtastic_config.json" ]]; then
    (
        cd "$APP_DIR"
        "$APP_DIR/.venv/bin/python" - "$APP_DIR" <<'PY'
import sys

from setup import auto_config, find_meshtastic_device
from config import save_config

app_dir = sys.argv[1]
device_path = find_meshtastic_device()
save_config(auto_config(app_dir=app_dir, dev_path=device_path))
print("Created auto-generated meshtastic_config.json.")
PY
    )
fi

if [[ ! -f "$APP_DIR/wifi_remote.conf" && -f "$APP_DIR/wifi_remote.conf.example" ]]; then
    cp "$APP_DIR/wifi_remote.conf.example" "$APP_DIR/wifi_remote.conf"
    chmod 600 "$APP_DIR/wifi_remote.conf"
    echo "Created local $APP_DIR/wifi_remote.conf from wifi_remote.conf.example."
fi

"$APP_DIR/.venv/bin/python" - "$APP_DIR" "$ADMIN_USERNAME" "$ADMIN_PASSWORD" "$ADMIN_CREDENTIALS_FILE" "$ADMIN_INSTALL_INFO_FILE" <<'PY'
import json
import os
import secrets
import sys

app_dir, username, password, credentials_file, install_info_file = sys.argv[1:6]
sys.path.insert(0, app_dir)

from admin_server import autogenerated_admin_config, make_password_hash

config_path = os.path.join(app_dir, "admin_config.json")
example_path = os.path.join(app_dir, "admin_config.json.example")

if os.path.exists(config_path):
    with open(config_path, "r", encoding="utf-8") as handle:
        config = json.load(handle)
else:
    with open(example_path, "r", encoding="utf-8") as handle:
        config = json.load(handle)

generated_config = autogenerated_admin_config(app_dir, config)
changed = generated_config != config
config = generated_config

needs_password_hash = not config.get("password_hash")
generated_password = False
if needs_password_hash and not password:
    password = secrets.token_urlsafe(12)
    generated_password = True

if not config.get("enabled"):
    config["enabled"] = True
    changed = True
if config.get("username") != username:
    config["username"] = username
    changed = True
if needs_password_hash:
    config["password_hash"] = make_password_hash(password)
    changed = True
if not config.get("session_secret") or config.get("session_secret") == "change-this-random-secret":
    config["session_secret"] = secrets.token_urlsafe(32)
    changed = True

if changed or not os.path.exists(config_path):
    with open(config_path, "w", encoding="utf-8") as handle:
        json.dump(config, handle, indent=4)
        handle.write("\n")
    os.chmod(config_path, 0o600)

if generated_password:
    with open(credentials_file, "w", encoding="utf-8") as handle:
        handle.write(f"MeshBoard Admin\nURL: http://<pi-ip>:8080\nUsername: {username}\nPassword: {password}\n")
    os.chmod(credentials_file, 0o600)
    print(f"Generated admin login saved to {credentials_file}")
    password_status = "generated"
elif needs_password_hash:
    print("Admin password was supplied with MESHBOARD_ADMIN_PASSWORD.")
    password_status = "supplied"
else:
    print("Existing admin password hash preserved.")
    password_status = "preserved"

with open(install_info_file, "w", encoding="utf-8") as handle:
    install_info = {
        "username": username,
        "password_status": password_status,
        "credentials_file": credentials_file,
    }
    if password_status in ("generated", "supplied"):
        install_info["password"] = password
    json.dump(install_info, handle)
    handle.write("\n")
os.chmod(install_info_file, 0o600)
PY

mkdir -p "$HOME/.config/systemd/user"
cp "$APP_DIR/systemd/meshboard.service" "$HOME/.config/systemd/user/$SERVICE_NAME"
if [[ "$APP_DIR" != "$HOME/MeshBoard" ]]; then
    sed -i "s|WorkingDirectory=%h/MeshBoard|WorkingDirectory=$APP_DIR|" "$HOME/.config/systemd/user/$SERVICE_NAME"
    sed -i "s|ExecStart=%h/MeshBoard/scripts/run_meshboard_forever.sh|ExecStart=$APP_DIR/scripts/run_meshboard_forever.sh|" "$HOME/.config/systemd/user/$SERVICE_NAME"
fi

sudo usermod -aG dialout "$(id -un)" || true
systemctl --user daemon-reload || true
systemctl --user enable "$SERVICE_NAME" || true
systemctl --user start "$SERVICE_NAME" || true

chmod +x "$APP_DIR/scripts/run_meshboard_forever.sh" "$APP_DIR/scripts/run_admin_forever.sh" "$APP_DIR/scripts/run_wifi_connect_forever.sh"

install_cron_entry() {
    local marker="$1"
    local schedule="$2"
    local command="$3"
    local current

    current="$(crontab -l 2>/dev/null || true)"
    if ! printf '%s\n' "$current" | grep -Fq "$marker"; then
        {
            printf '%s\n' "$current"
            printf '%s %s # %s\n' "$schedule" "$command" "$marker"
        } | crontab -
    fi
}

remove_cron_entry() {
    local marker="$1"
    local current

    current="$(crontab -l 2>/dev/null || true)"
    printf '%s\n' "$current" | grep -Fv "$marker" | crontab -
}

quote_shell() {
    local value="$1"
    printf "'%s'" "${value//\'/\'\\\'\'}"
}

quoted_app_dir="$(quote_shell "$APP_DIR")"
remove_cron_entry "meshboard-bbs"
remove_cron_entry "run_meshboard_forever.sh"
install_cron_entry "meshboard-admin" "@reboot" "APP_DIR=$quoted_app_dir $quoted_app_dir/scripts/run_admin_forever.sh"
install_cron_entry "meshboard-wifi" "@reboot" "APP_DIR=$quoted_app_dir $quoted_app_dir/scripts/run_wifi_connect_forever.sh"
install_cron_entry "meshboard-daily-backup" "@daily" "cd $quoted_app_dir && $quoted_app_dir/.venv/bin/python $quoted_app_dir/backup_manager.py --daily"

(
    cd "$APP_DIR"
    "$APP_DIR/.venv/bin/python" "$APP_DIR/backup_manager.py" --daily >/dev/null 2>&1 || true
)

nohup env APP_DIR="$APP_DIR" "$APP_DIR/scripts/run_admin_forever.sh" >/dev/null 2>&1 &
nohup env APP_DIR="$APP_DIR" "$APP_DIR/scripts/run_wifi_connect_forever.sh" >/dev/null 2>&1 &

pi_ips="$(hostname -I 2>/dev/null | tr ' ' '\n' | awk '/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && $0 !~ /^169\.254\./ { print }' | paste -sd ' ' -)"
admin_url="http://<pi-ip>:8080"
first_ip="$(printf '%s\n' "$pi_ips" | awk '{ print $1 }')"
if [[ -n "$first_ip" ]]; then
    admin_url="http://$first_ip:8080"
fi

admin_username="$ADMIN_USERNAME"
password_status="unknown"
admin_password=""
if [[ -f "$ADMIN_INSTALL_INFO_FILE" ]]; then
    admin_username="$("$APP_DIR/.venv/bin/python" - "$ADMIN_INSTALL_INFO_FILE" "$ADMIN_USERNAME" <<'PY'
import json
import sys

path, fallback = sys.argv[1:3]
try:
    with open(path, "r", encoding="utf-8") as handle:
        print(json.load(handle).get("username") or fallback)
except Exception:
    print(fallback)
PY
)"
    password_status="$("$APP_DIR/.venv/bin/python" - "$ADMIN_INSTALL_INFO_FILE" <<'PY'
import json
import sys

try:
    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        print(json.load(handle).get("password_status") or "unknown")
except Exception:
    print("unknown")
PY
)"
    admin_password="$("$APP_DIR/.venv/bin/python" - "$ADMIN_INSTALL_INFO_FILE" <<'PY'
import json
import sys

try:
    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        print(json.load(handle).get("password") or "")
except Exception:
    print("")
PY
)"
fi

echo "Installed MeshBoard to $APP_DIR."
echo "MeshBoard, the admin website, and the WiFi helper were installed at boot and started now."
echo "Daily backups were enabled; restore points are stored in $APP_DIR/backups."
echo "Local AI uses Ollama model $OLLAMA_MODEL when installed and starts only when users open Local AI."
echo "Edit $APP_DIR/wifi_remote.conf later if you want the Pi to join a phone hotspot."
echo
echo "Admin website:"
echo "  URL: $admin_url"
if [[ -n "$pi_ips" ]]; then
    echo "  Pi IPs: $pi_ips"
fi
echo "  Username: $admin_username"
if [[ "$password_status" == "generated" || "$password_status" == "supplied" ]]; then
    echo "  Password: $admin_password"
elif [[ -f "$ADMIN_CREDENTIALS_FILE" ]]; then
    echo "  Password: already configured; see $ADMIN_CREDENTIALS_FILE if this install generated it earlier."
else
    echo "  Password: already configured in $APP_DIR/admin_config.json"
fi
echo "  Saved login file: $ADMIN_CREDENTIALS_FILE"
